version: '3'

networks:
  backend:
    external: true

services:
  mysql_57:
    image: mysql:5.7
    container_name: mysql_57
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_57/data:/var/lib/mysql
      - ./mysql/mysql_57/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql_57/logs:/var/log/mysql/
      - ./mysql/mysql_57/dump:/dump
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    networks:
      - backend 
      
  mysql_8019:
    image: mysql:8.0.19
    container_name: mysql_8019
    ports:
      - "3307:3307"
    volumes:
      - ./mysql/mysql_8019/data:/var/lib/mysql
      - ./mysql/mysql_8019/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql_8019/logs:/var/log/mysql/
      - ./mysql/mysql_8019/dump:/dump
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    networks:
      - backend
      
  mysql_8030:
    image: mysql:8.0.30
    container_name: mysql_8030
    ports:
      - "3308:3308"
    volumes:
      - ./mysql/mysql_8030/data:/var/lib/mysql
      - ./mysql/mysql_8030/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql_8030/logs:/var/log/mysql/
      - ./mysql/mysql_8030/dump:/dump
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    networks:
      - backend