version: '3'

networks:
  backend:
    external: true

services:
  php56:
    container_name: php56
    # Собираем образ PHP на основе Dockerfile
    build: ./php/5.6
    # монтируем директорию с проектами
    volumes:
      - ~/docker/www:/var/www
    networks:
        - backend
  php72:
    container_name: php72
    build: ./php/7.2
    volumes:
      - ~/docker/www:/var/www
    networks:
        - backend
  php81:
    container_name: php81
    build: ./php/8.1
    volumes:
      - ~/docker/www:/var/www
    networks:
        - backend